[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "day09"
path = "day09/main.rs"


[dependencies]
ncurses = "5.101.0"
